# Generated by Django 3.2.4 on 2021-06-30 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0003_alter_documento_criadopor'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='documento',
            field=models.FileField(default=1, upload_to='documentos'),
            preserve_default=False,
        ),
    ]
