# Generated by Django 3.2.4 on 2021-07-05 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0004_documento_documento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='criadoPor',
            new_name='pertence',
        ),
    ]
